---
ansible_connection: winrm
ansible_user: ".\\localuser"
ansible_password: "password"
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_operation_timeout_sec: 400
ansible_winrm_read_timeout_sec: 500

