ludus:
  - vm_name: "{{ range_id }}-dc01"
    hostname: "{{ range_id }}-dc01"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 10
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - ccdc_dc2019

  - vm_name: "{{ range_id }}-file01"
    hostname: "{{ range_id }}-file01"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 20
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - ccdc_fileserver

  - vm_name: "{{ range_id }}-web01"
    hostname: "{{ range_id }}-web01"
    template: ubuntu-22.04-x64-server-template
    vlan: 10
    ip_last_octet: 30
    ram_gb: 4
    cpus: 2
    linux: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - ccdc_web

  - vm_name: "{{ range_id }}-db01"
    hostname: "{{ range_id }}-db01"
    template: ubuntu-22.04-x64-server-template
    vlan: 10
    ip_last_octet: 40
    ram_gb: 4
    cpus: 2
    linux: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - ccdc_db

  - vm_name: "{{ range_id }}-mail01"
    hostname: "{{ range_id }}-mail01"
    template: ubuntu-22.04-x64-server-template
    vlan: 10
    ip_last_octet: 50
    ram_gb: 4
    cpus: 2
    linux: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - ccdc_mail

  - vm_name: "{{ range_id }}-soc01"
    hostname: "{{ range_id }}-soc01"
    template: ubuntu-22.04-x64-server-template
    vlan: 10
    ip_last_octet: 60
    ram_gb: 4
    cpus: 2
    linux: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - ccdc_soc

  - vm_name: "{{ range_id }}-ws01"
    hostname: "{{ range_id }}-ws01"
    template: win10-21h1-x64-enterprise-template
    vlan: 20
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - ccdc_workstation

  - vm_name: "{{ range_id }}-ws02"
    hostname: "{{ range_id }}-ws02"
    template: win10-21h1-x64-enterprise-template
    vlan: 20
    ip_last_octet: 11
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - ccdc_workstation

  - vm_name: "{{ range_id }}-kali01"
    hostname: "{{ range_id }}-kali01"
    template: kali-x64-desktop-template
    vlan: 30
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    linux: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - ccdc_kali_attacker
