---
# roles/ccdc_dc2019/tasks/main.yml
# DC01 - Windows Server 2019 Domain Controller tasks

- import_tasks: install_ad.yml
- import_tasks: promote.yml
- import_tasks: post.yml
- import_tasks: scenario.yml

